import { sendEmptyWebPush } from '../../../shared/webPush.js';
import { resolveSupabaseBackendCredential, supabaseBackendHeaders } from '../../../functions/api/_shared/supabaseBackend.js';

const INGV_SOURCE = 'https://www.ct.ingv.it/sezioniesterne/Comunicati/ComunicatiVulcanici.php';
const PUBLIC_CATEGORIES = new Set(['etna_updates','etna_weekly','experiences','events','news','promotions']);
const CUSTOMER_CATEGORIES = new Set(['customer_booking_confirmed','customer_payment_received','customer_upcoming_reminder','customer_operational_change','customer_booking_rescheduled','customer_booking_cancelled','customer_review_reminder']);
const CRITICAL_ADMIN = new Set(['security_alerts']);
function nowIso(){return new Date().toISOString();}
function uuid(){return crypto.randomUUID();}
function text(value,max=500){return String(value??'').trim().replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').slice(0,max);}
async function digest(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value)));return [...new Uint8Array(d)].map((b)=>b.toString(16).padStart(2,'0')).join('');}
function parseJson(value,fallback=[]){try{return JSON.parse(value);}catch{return fallback;}}
function endpointValid(value){try{return new URL(value).protocol==='https:';}catch{return false;}}
function stripHtml(value){return text(String(value||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'"),1000);}
function absoluteUrl(href){try{return new URL(href,INGV_SOURCE).toString();}catch{return INGV_SOURCE;}}
function classifyEtna(description){const d=description.toUpperCase();if(/PRIMO COMUNICATO|INIZIO/.test(d))return'event_started';if(/FINE FENOMENO|FINE DELL|RIENTRO/.test(d))return'event_ended';if(/BOLLETTINO.*SETTIMAN|SETTIMANALE/.test(d))return'weekly_bulletin';return'activity_update';}
function parseEtnaRows(html){
  const rows=[]; const rowPattern=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi; let match;
  while((match=rowPattern.exec(html))){const raw=match[1];const plain=stripHtml(raw);if(!/\bETNA\b/i.test(plain))continue;const href=raw.match(/href=["']([^"']+\.pdf(?:\?[^"']*)?)["']/i)?.[1]||raw.match(/href=["']([^"']+)["']/i)?.[1]||'';const date=plain.match(/\b(\d{4}[-\/]\d{2}[-\/]\d{2}(?:\s+\d{2}:\d{2}(?::\d{2})?)?|\d{2}[-\/]\d{2}[-\/]\d{4}(?:\s+\d{2}:\d{2})?)\b/)?.[1]||'';rows.push({description:plain,date,sourceUrl:absoluteUrl(href)});}
  return rows.slice(0,30);
}
function localMinutes(date,timezone){try{const p=new Intl.DateTimeFormat('en-GB',{timeZone:timezone||'Europe/Rome',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);return Number(p.find((x)=>x.type==='hour')?.value||0)*60+Number(p.find((x)=>x.type==='minute')?.value||0);}catch{return null;}}
function quiet(pref,date=new Date()){if(!pref.quiet_hours_enabled||!pref.quiet_start||!pref.quiet_end)return false;const to=(v)=>Number(v.slice(0,2))*60+Number(v.slice(3));const n=localMinutes(date,pref.timezone);if(n===null)return false;const s=to(pref.quiet_start),e=to(pref.quiet_end);return s===e?false:s<e?n>=s&&n<e:n>=s||n<e;}
async function increment(db,key,amount=1){const day=nowIso().slice(0,10);await db.prepare('INSERT INTO notification_usage_counters(counter_date,counter_key,counter_value,updated_at) VALUES(?,?,?,?) ON CONFLICT(counter_date,counter_key) DO UPDATE SET counter_value=counter_value+excluded.counter_value,updated_at=excluded.updated_at').bind(day,key,amount,nowIso()).run();}
async function budget(db,env){const day=nowIso().slice(0,10);const row=await db.prepare("SELECT counter_value FROM notification_usage_counters WHERE counter_date=? AND counter_key='push_attempts'").bind(day).first();const attempts=Number(row?.counter_value||0),cap=Math.max(1,Number(env.NOTIFICATION_PUBLIC_DAILY_SEND_CAP||1000)),pct=attempts/cap*100;const w=Number(env.NOTIFICATION_WARNING_PERCENT||70),c=Number(env.NOTIFICATION_CONSERVATION_PERCENT||85),h=Number(env.NOTIFICATION_HARD_STOP_PERCENT||95);return{attempts,cap,percent:Number(pct.toFixed(1)),mode:pct>=h?'HARD_SAFETY':pct>=c?'CONSERVATION':pct>=w?'WARNING':'NORMAL'};}
function budgetAllows(mode,event){if(mode==='NORMAL'||mode==='WARNING')return true;if(mode==='CONSERVATION')return !['promotions','daily_summary','weekly_summary','etna_weekly'].includes(event.category);if(mode==='HARD_SAFETY')return event.audience==='admin'&&event.priority==='critical';return true;}
async function audit(db,type,fields={}){await db.prepare('INSERT INTO notification_audit_log(id,event_type,audience,actor_id,subscription_id,campaign_id,outcome,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(uuid(),type,fields.audience||null,fields.actorId||null,fields.subscriptionId||null,fields.campaignId||null,fields.outcome||'ok',fields.metadata?JSON.stringify(fields.metadata):null,nowIso()).run();}
async function deliver(db,env,event){
  const personalized=CUSTOMER_CATEGORIES.has(event.category);if(personalized&&(!event.recipient_subscription_id||event.audience!=='public'))throw new Error('personalized_recipient_required');
  const b=await budget(db,env);if(!budgetAllows(b.mode,event)){await audit(db,'notification_suppressed_budget',{audience:event.audience,outcome:b.mode,metadata:{category:event.category}});return{attempted:0,sent:0,failed:0,suppressed:true,budget:b};}
  const cap=Math.max(1,Math.min(1000,Number(env.NOTIFICATION_BROADCAST_BATCH_CAP||250)));
  const base='SELECT s.*,p.resolved_locale,p.categories_json,p.quiet_hours_enabled,p.quiet_start,p.quiet_end,p.timezone FROM notification_subscriptions s JOIN notification_preferences p ON p.subscription_id=s.id WHERE s.audience=? AND s.enabled=1';
  const targeted=Boolean(event.recipient_subscription_id);
  const statement=db.prepare(`${base}${targeted?' AND s.id=?':''} LIMIT ${cap}`);
  const rows=targeted?await statement.bind(event.audience,event.recipient_subscription_id).all():await statement.bind(event.audience).all();
  let attempted=0,sent=0,failed=0;
  for(const sub of rows.results||[]){const cats=parseJson(sub.categories_json,[]);if(!personalized&&!cats.includes(event.category))continue;if(event.language_target&&event.language_target!=='all'&&sub.resolved_locale!==event.language_target)continue;const locale=sub.resolved_locale==='en'?'en':'it';const title=locale==='it'?event.title_it:event.title_en,body=locale==='it'?event.body_it:event.body_en;await db.prepare('INSERT INTO notification_inbox(id,event_id,subscription_id,audience,category,title,body,destination_url,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(uuid(),event.id,sub.id,event.audience,event.category,title,body,event.destination_url||null,nowIso()).run();if((quiet(sub)&&event.priority!=='critical')||!endpointValid(sub.endpoint))continue;attempted++;await increment(db,'push_attempts');const push=await sendEmptyWebPush(sub,env,{urgency:event.priority==='critical'?'high':'normal'});if(push.ok){sent++;await increment(db,'push_success');}else{failed++;await increment(db,'push_failed');if(push.dead)await db.prepare('UPDATE notification_subscriptions SET endpoint=?,p256dh=NULL,auth=NULL,enabled=1,updated_at=? WHERE id=?').bind(`inapp://${event.audience}/${(await digest(sub.device_id)).slice(0,32)}`,nowIso(),sub.id).run();}}
  return{attempted,sent,failed,suppressed:false,budget:b,targeted};
}
async function queueAndDeliver(db,env,event){
  const existing=await db.prepare('SELECT id FROM notification_events WHERE dedupe_key=?').bind(event.dedupe_key).first();if(existing)return{deduped:true};event.id=event.id||uuid();await db.prepare('INSERT INTO notification_events(id,audience,category,origin,title_it,body_it,title_en,body_en,destination_url,dedupe_key,priority,created_at,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(event.id,event.audience,event.category,event.origin,event.title_it,event.body_it,event.title_en,event.body_en,event.destination_url||null,event.dedupe_key,event.priority||'normal',nowIso(),'sending').run();const result=await deliver(db,env,event);await db.prepare("UPDATE notification_events SET status='sent',sent_at=? WHERE id=?").bind(nowIso(),event.id).run();return result;
}
async function pollEtna(db,env){
  const response=await fetch(INGV_SOURCE,{headers:{'User-Agent':'vulcanIQ official-source monitor/1.0'}});if(!response.ok)throw new Error(`ingv_http_${response.status}`);const html=await response.text();const rows=parseEtnaRows(html);if(!rows.length)throw new Error('ingv_no_etna_rows');const existingCount=Number((await db.prepare("SELECT count(*) AS total FROM notification_source_dedupe WHERE source='INGV_OE_ETNA'").first())?.total||0);let newCount=0;
  for(const row of [...rows].reverse()){const sourceIdentifier=await digest(`${row.date}|${row.description}|${row.sourceUrl}`);const dedupe=`ingv:${sourceIdentifier}`;const exists=await db.prepare('SELECT dedupe_key FROM notification_source_dedupe WHERE dedupe_key=?').bind(dedupe).first();if(exists)continue;newCount++;const classification=classifyEtna(row.description);await db.prepare('INSERT INTO notification_source_dedupe(dedupe_key,source,source_url,source_identifier,official_timestamp,retrieved_at,classification,content_hash) VALUES(?,?,?,?,?,?,?,?)').bind(dedupe,'INGV_OE_ETNA',row.sourceUrl,sourceIdentifier,row.date||null,nowIso(),classification,await digest(row.description)).run();if(existingCount===0)continue;
    const category=classification==='weekly_bulletin'?'etna_weekly':'etna_updates';if(classification==='activity_update'){const hours=Math.max(1,Number(env.ETNA_ROUTINE_MIN_INTERVAL_HOURS||6));const recent=await db.prepare("SELECT created_at FROM notification_events WHERE origin='ingv_etna' AND category='etna_updates' AND created_at>=? ORDER BY created_at DESC LIMIT 1").bind(new Date(Date.now()-hours*3600000).toISOString()).first();if(recent)continue;}
    await queueAndDeliver(db,env,{audience:'public',category,origin:'ingv_etna',title_it:'Aggiornamento Etna',body_it:"INGV ha pubblicato un nuovo aggiornamento sull'attività dell'Etna. Tocca per i dettagli ufficiali.",title_en:'Etna update',body_en:'INGV has published a new update on Mount Etna activity. Tap for the official details.',destination_url:row.sourceUrl,dedupe_key:`event:${dedupe}`,priority:['event_started','event_ended'].includes(classification)?'high':'normal'});
  }
  await increment(db,'etna_source_checks');return{rows:rows.length,newCount,baseline:existingCount===0};
}
async function processCampaigns(db,env){const due=await db.prepare("SELECT * FROM notification_campaigns WHERE status='scheduled' AND scheduled_for<=? ORDER BY scheduled_for ASC LIMIT 25").bind(nowIso()).all();for(const c of due.results||[]){const claimedAt=nowIso();const claim=await db.prepare("UPDATE notification_campaigns SET status='processing',processing_at=?,updated_at=? WHERE id=? AND status='scheduled'").bind(claimedAt,claimedAt,c.id).run();if(!claim.meta?.changes)continue;try{const event={audience:'public',category:c.category,origin:'admin_campaign',title_it:c.title_it||c.title_en,body_it:c.body_it||c.body_en,title_en:c.title_en||c.title_it,body_en:c.body_en||c.body_it,destination_url:c.destination_url||'/',dedupe_key:c.dedupe_key,priority:'normal',language_target:c.language_target||'all'};const result=await queueAndDeliver(db,env,event);await db.prepare("UPDATE notification_campaigns SET status='sent',sent_at=?,updated_at=?,failure_reason=NULL WHERE id=? AND status='processing'").bind(nowIso(),nowIso(),c.id).run();await audit(db,'campaign_sent',{audience:'public',campaignId:c.id,metadata:result});}catch(error){const reason=String(error?.message||error).slice(0,240);await db.prepare("UPDATE notification_campaigns SET status='failed',failure_reason=?,updated_at=? WHERE id=? AND status='processing'").bind(reason,nowIso(),c.id).run();await audit(db,'campaign_failed',{audience:'public',campaignId:c.id,outcome:'failed',metadata:{error:reason.slice(0,120)}});}}}
async function deliverOwnedJob(db,env,job){
  const ownership=job.ownership_id&&job.recipient_subscription_id?await db.prepare('SELECT id,push_enabled,inapp_enabled FROM notification_subscription_ownership WHERE id=? AND subscription_id=? AND revoked_at IS NULL LIMIT 1').bind(job.ownership_id,job.recipient_subscription_id).first():null;
  if(!ownership){await db.prepare("UPDATE notification_jobs SET status='cancelled',cancelled_at=?,failure_reason='owned_recipient_unavailable',terminal_reason='revoked_recipient' WHERE id=? AND status='processing'").bind(nowIso(),job.id).run();return{status:'cancelled',reason:'owned_recipient_unavailable'};}
  const sub=await db.prepare('SELECT s.*,p.resolved_locale,p.quiet_hours_enabled,p.quiet_start,p.quiet_end,p.timezone FROM notification_subscriptions s JOIN notification_preferences p ON p.subscription_id=s.id WHERE s.id=? AND s.audience=\'public\' AND s.enabled=1 LIMIT 1').bind(job.recipient_subscription_id).first();
  if(!sub){await db.prepare("UPDATE notification_jobs SET status='cancelled',cancelled_at=?,failure_reason='owned_recipient_unavailable',terminal_reason='dead_subscription' WHERE id=? AND status='processing'").bind(nowIso(),job.id).run();return{status:'cancelled',reason:'owned_recipient_unavailable'};}
  const eventKey=`automation:${job.dedupe_key}`;let event=await db.prepare('SELECT id FROM notification_events WHERE dedupe_key=? LIMIT 1').bind(eventKey).first();
  if(!event){const id=uuid();await db.prepare("INSERT OR IGNORE INTO notification_events(id,audience,category,origin,title_it,body_it,title_en,body_en,destination_url,dedupe_key,priority,created_at,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,'public',job.category,'automation_job',job.title_it,job.body_it,job.title_en,job.body_en,job.destination_url||'/',eventKey,job.priority||'normal',nowIso(),'sending').run();event=await db.prepare('SELECT id FROM notification_events WHERE dedupe_key=? LIMIT 1').bind(eventKey).first();}
  if(ownership.inapp_enabled!==0&&!job.inbox_delivered_at){const locale=sub.resolved_locale==='en'?'en':'it';await db.prepare('INSERT OR IGNORE INTO notification_inbox(id,event_id,subscription_id,audience,category,title,body,destination_url,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(uuid(),event.id,sub.id,'public',job.category,locale==='it'?job.title_it:job.title_en,locale==='it'?job.body_it:job.body_en,job.destination_url||'/',nowIso()).run();await db.prepare('UPDATE notification_jobs SET inbox_delivered_at=coalesce(inbox_delivered_at,?) WHERE id=?').bind(nowIso(),job.id).run();}
  if(ownership.push_enabled===0||!endpointValid(sub.endpoint)||(quiet(sub)&&job.priority!=='critical')){await db.prepare("UPDATE notification_jobs SET status='sent',sent_at=?,failure_reason=NULL,terminal_reason=? WHERE id=? AND status='processing'").bind(nowIso(),ownership.push_enabled===0?'push_disabled':!endpointValid(sub.endpoint)?'inapp_only':'quiet_hours_inapp_only',job.id).run();return{status:'sent',push:'skipped'};}
  if(job.push_delivered_at){await db.prepare("UPDATE notification_jobs SET status='sent',sent_at=coalesce(sent_at,?),failure_reason=NULL WHERE id=? AND status='processing'").bind(nowIso(),job.id).run();return{status:'sent',deduped:true};}
  if(job.push_started_at){await db.prepare("UPDATE notification_jobs SET status='failed',failure_reason='push_outcome_unknown',terminal_reason='push_outcome_unknown' WHERE id=? AND status='processing'").bind(job.id).run();return{status:'failed',reason:'push_outcome_unknown'};}
  const attempt=Number(job.attempt_count||0)+1,maxAttempts=Math.max(1,Number(job.max_attempts||3)),started=nowIso();
  await db.prepare('UPDATE notification_jobs SET attempt_count=?,last_attempt_at=?,push_started_at=? WHERE id=? AND status=\'processing\'').bind(attempt,started,started,job.id).run();await increment(db,'push_attempts');
  const push=await sendEmptyWebPush(sub,env,{urgency:job.priority==='critical'?'high':'normal'});
  if(push.ok){await increment(db,'push_success');await db.batch([db.prepare("UPDATE notification_jobs SET status='sent',sent_at=?,push_delivered_at=?,failure_reason=NULL,terminal_reason=NULL WHERE id=? AND status='processing'").bind(nowIso(),nowIso(),job.id),db.prepare("UPDATE notification_events SET status='sent',sent_at=? WHERE id=?").bind(nowIso(),event.id),db.prepare("INSERT OR IGNORE INTO notification_delivery_attempts(id,job_id,attempt_number,transport,outcome,http_status,created_at) VALUES(?,?,?,'push','sent',?,?)").bind(uuid(),job.id,attempt,push.status,nowIso())]);return{status:'sent',push:'sent'};}
  await increment(db,'push_failed');
  if(push.dead){await db.batch([db.prepare('UPDATE notification_subscriptions SET endpoint=?,p256dh=NULL,auth=NULL,enabled=1,updated_at=? WHERE id=?').bind(`inapp://public/${(await digest(sub.device_id)).slice(0,32)}`,nowIso(),sub.id),db.prepare("UPDATE notification_jobs SET status='sent',sent_at=?,dead_subscription_at=?,failure_reason='dead_subscription',terminal_reason='dead_subscription' WHERE id=? AND status='processing'").bind(nowIso(),nowIso(),job.id),db.prepare("INSERT OR IGNORE INTO notification_delivery_attempts(id,job_id,attempt_number,transport,outcome,http_status,error_code,created_at) VALUES(?,?,?,'push','permanent_error',?,'dead_subscription',?)").bind(uuid(),job.id,attempt,push.status,nowIso())]);return{status:'sent',push:'dead_subscription'};}
  if((push.status===429||push.status>=500)&&attempt<maxAttempts){const delay=Math.min(3600,60*(2**Math.min(attempt-1,6))),next=new Date(Date.now()+delay*1000).toISOString();await db.batch([db.prepare("UPDATE notification_jobs SET status='scheduled',next_attempt_at=?,push_started_at=NULL,failure_reason='retryable_push_error' WHERE id=? AND status='processing'").bind(next,job.id),db.prepare("INSERT OR IGNORE INTO notification_delivery_attempts(id,job_id,attempt_number,transport,outcome,http_status,error_code,created_at) VALUES(?,?,?,'push','retryable_error',?,'retryable_push_error',?)").bind(uuid(),job.id,attempt,push.status,nowIso())]);return{status:'deferred',nextAttemptAt:next};}
  const unknown=push.status===0,reason=unknown?'push_outcome_unknown':attempt>=maxAttempts?'max_attempts_exhausted':'permanent_push_error';await db.batch([db.prepare('UPDATE notification_jobs SET status=\'failed\',failure_reason=?,terminal_reason=? WHERE id=? AND status=\'processing\'').bind(reason,reason,job.id),db.prepare("INSERT OR IGNORE INTO notification_delivery_attempts(id,job_id,attempt_number,transport,outcome,http_status,error_code,created_at) VALUES(?,?,?,'push',?,?,?,?)").bind(uuid(),job.id,attempt,unknown?'outcome_unknown':'permanent_error',push.status||null,reason,nowIso())]);return{status:'failed',reason};
}
async function processAutomationJobs(db,env){
  const current=nowIso();const due=await db.prepare("SELECT j.*,r.enabled AS rule_enabled FROM notification_jobs j LEFT JOIN notification_automation_rules r ON r.rule_key=j.rule_key WHERE j.status='scheduled' AND j.scheduled_for<=? AND (j.next_attempt_at IS NULL OR j.next_attempt_at<=?) ORDER BY coalesce(j.next_attempt_at,j.scheduled_for) ASC LIMIT 50").bind(current,current).all();let processed=0;
  for(const job of due.results||[]){const claimedAt=nowIso();const claim=await db.prepare("UPDATE notification_jobs SET status='processing',processing_at=? WHERE id=? AND status='scheduled'").bind(claimedAt,job.id).run();if(!claim.meta?.changes)continue;if(job.rule_key&&job.rule_enabled===0){await db.prepare("UPDATE notification_jobs SET status='cancelled',cancelled_at=?,failure_reason='rule_disabled',terminal_reason='rule_disabled' WHERE id=? AND status='processing'").bind(nowIso(),job.id).run();await audit(db,'automation_job_cancelled',{audience:job.audience,outcome:'rule_disabled',metadata:{jobId:job.id,ruleKey:job.rule_key}});continue;}
    try{if(CUSTOMER_CATEGORIES.has(job.category)){const result=await deliverOwnedJob(db,env,job);if(result.status==='sent')processed++;await audit(db,result.status==='sent'?'automation_job_sent':result.status==='deferred'?'automation_job_deferred':result.status==='cancelled'?'automation_job_cancelled':'automation_job_failed',{audience:'public',outcome:result.status,metadata:{jobId:job.id,ruleKey:job.rule_key,...result}});continue;}const event={audience:job.audience,category:job.category,origin:'automation_job',title_it:job.title_it,body_it:job.body_it,title_en:job.title_en,body_en:job.body_en,destination_url:job.destination_url||'/',dedupe_key:`automation:${job.dedupe_key}`,priority:job.priority||'normal',recipient_subscription_id:job.recipient_subscription_id||null};const result=await queueAndDeliver(db,env,event);if(result.suppressed){await db.prepare("UPDATE notification_jobs SET status='cancelled',cancelled_at=?,failure_reason='budget_suppression' WHERE id=? AND status='processing'").bind(nowIso(),job.id).run();}else{await db.prepare("UPDATE notification_jobs SET status='sent',sent_at=?,failure_reason=NULL WHERE id=? AND status='processing'").bind(nowIso(),job.id).run();processed++;}await audit(db,result.suppressed?'automation_job_cancelled':'automation_job_sent',{audience:job.audience,outcome:result.suppressed?'budget_suppression':'ok',metadata:{jobId:job.id,ruleKey:job.rule_key,...result}});}catch(error){const reason=String(error?.message||error).slice(0,240);await db.prepare("UPDATE notification_jobs SET status='failed',failure_reason=?,terminal_reason='worker_exception' WHERE id=? AND status='processing'").bind(reason,job.id).run();await audit(db,'automation_job_failed',{audience:job.audience,outcome:'failed',metadata:{jobId:job.id,ruleKey:job.rule_key,error:reason.slice(0,120)}});}}
  return{due:(due.results||[]).length,processed};
}
async function pollPublicExcursions(db,env){
  const url=text(env.SUPABASE_URL||env.VITE_SUPABASE_URL,300).replace(/\/$/,'');const anon=env.SUPABASE_ANON_KEY||env.VITE_SUPABASE_ANON_KEY;if(!url||!anon)return{skipped:true};const today=new Date();const from=today.toISOString().slice(0,10),to=new Date(today.getTime()+48*3600000).toISOString().slice(0,10);const params=new URLSearchParams({select:'id,date,start_time,title_it,title_en,active,public_visibility',active:'eq.true',public_visibility:'eq.true',order:'date.asc,start_time.asc',limit:'100'});params.append('date',`gte.${from}`);params.append('date',`lte.${to}`);const response=await fetch(`${url}/rest/v1/public_fixed_excursions?${params}`,{headers:{apikey:anon,Authorization:`Bearer ${anon}`,Accept:'application/json'}});if(!response.ok)return{skipped:true,status:response.status};const rows=await response.json();for(const item of Array.isArray(rows)?rows:[]){if(item.date>to)continue;const key=`fixed_excursion_48h:${item.id}:${item.date}`;await queueAndDeliver(db,env,{audience:'public',category:'experiences',origin:'vulcaniq_domain',title_it:'Esperienza vulcanIQ in arrivo',body_it:`${text(item.title_it||'Escursione sull’Etna',100)} · ${item.date}${item.start_time?` · ${item.start_time.slice(0,5)}`:''}`,title_en:'Upcoming vulcanIQ experience',body_en:`${text(item.title_en||item.title_it||'Mount Etna experience',100)} · ${item.date}${item.start_time?` · ${item.start_time.slice(0,5)}`:''}`,destination_url:'/experiences',dedupe_key:key,priority:'normal'});}return{rows:Array.isArray(rows)?rows.length:0};
}
async function pollAdminUpcoming(db,env){
  const url=text(env.SUPABASE_URL||env.VITE_SUPABASE_URL,300).replace(/\/$/,'');const backendCredential=resolveSupabaseBackendCredential(env);if(!url||!backendCredential)return{skipped:true};const tomorrow=new Date(Date.now()+24*3600000).toISOString().slice(0,10);const params=new URLSearchParams({select:'id,requested_date,status',requested_date:`eq.${tomorrow}`,status:'eq.accepted',limit:'100'});const response=await fetch(`${url}/rest/v1/booking_requests?${params}`,{headers:supabaseBackendHeaders(backendCredential,{headers:{Accept:'application/json'}})});if(!response.ok)return{skipped:true,status:response.status};const rows=await response.json();if(Array.isArray(rows)&&rows.length){await queueAndDeliver(db,env,{audience:'admin',category:'upcoming_excursions',origin:'vulcaniq_domain',title_it:'Escursioni di domani',body_it:`${rows.length} prenotazion${rows.length===1?'e':'i'} richiedono attenzione per domani.`,title_en:'Tomorrow’s excursions',body_en:`${rows.length} booking${rows.length===1?'':'s'} need attention for tomorrow.`,destination_url:'/admin/upcoming',dedupe_key:`admin_upcoming:${tomorrow}`,priority:'normal'});}return{rows:Array.isArray(rows)?rows.length:0};
}
async function runScheduled(env){const db=env.NOTIFICATIONS_DB;if(!db)throw new Error('notifications_db_not_configured');const cap=Math.max(1,Number(env.NOTIFICATION_CRON_PROCESSING_CAP||100));await increment(db,'cron_runs');const results={};try{results.automationJobs=await processAutomationJobs(db,env);}catch(e){results.automationJobs={error:String(e.message||e)};}try{results.campaigns=await processCampaigns(db,env);}catch(e){results.campaigns={error:String(e.message||e)};}try{results.etna=await pollEtna(db,env);}catch(e){results.etna={error:String(e.message||e)};await audit(db,'notification_send_failed',{audience:'public',outcome:'etna_source_failure',metadata:{error:String(e.message||e).slice(0,120)}});}if(cap>2){try{results.experiences=await pollPublicExcursions(db,env);}catch(e){results.experiences={error:String(e.message||e)};}try{results.adminUpcoming=await pollAdminUpcoming(db,env);}catch(e){results.adminUpcoming={error:String(e.message||e)};}}return results;}

export { budgetAllows, classifyEtna, endpointValid, parseEtnaRows, processAutomationJobs, processCampaigns, quiet, runScheduled };

export default {
  async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/health'){const b=env.NOTIFICATIONS_DB?await budget(env.NOTIFICATIONS_DB,env):null;return Response.json({ok:Boolean(env.NOTIFICATIONS_DB),budget:b,source:INGV_SOURCE},{headers:{'Cache-Control':'no-store'}});}return new Response('Not found',{status:404});},
  async scheduled(_controller,env,ctx){ctx.waitUntil(runScheduled(env));}
};
