import React, { useEffect, useMemo, useState } from 'react';
import {
  capabilityState, createNotificationCampaign, disableNotifications, dismissNotification, enableNotifications,
  ensureNotificationDevice, getNotificationHealth, getNotificationPreferences, installState, listNotificationCampaigns, listNotificationInbox,
  markNotificationRead, promptInstall, sendTestNotification, updateNotificationPreferences
} from '../../services/notificationService.js';
import './notifications.css';

const PUBLIC_OPTIONS = [
  ['etna_updates','Official Etna updates','Aggiornamenti ufficiali Etna'], ['etna_weekly','Weekly Etna summary','Riepilogo settimanale Etna'],
  ['experiences','Upcoming experiences','Prossime esperienze'], ['events','Events','Eventi'], ['news','News','Notizie'], ['promotions','Promotions & discounts','Promozioni e sconti']
];
const ADMIN_OPTIONS = [
  ['new_bookings','New bookings','Nuove prenotazioni'], ['upcoming_excursions','Upcoming excursions','Prossime escursioni'], ['gift_cards','Gift Cards','Gift Card'], ['booking_codes','Booking codes','Codici prenotazione'], ['payment_reconciliation','Payment / reconciliation','Pagamenti / riconciliazione'], ['operational_failures','Operational failures','Errori operativi'], ['security_alerts','Security alerts','Avvisi sicurezza'], ['daily_summary','Daily summary','Riepilogo giornaliero'], ['weekly_summary','Weekly summary','Riepilogo settimanale']
];
function c(lang,it,en){return lang==='it'?it:en;}
function defaultCategories(variant){return variant==='admin'?ADMIN_OPTIONS.slice(0,7).map(([key])=>key):PUBLIC_OPTIONS.slice(0,5).map(([key])=>key);}

function InstallCard({variant,lang}){
  const [state,setState]=useState(()=>installState());
  useEffect(()=>{const sync=()=>setState(installState());window.addEventListener('vulcaniq-install-state-changed',sync);return()=>window.removeEventListener('vulcaniq-install-state-changed',sync);},[]);
  const name=variant==='admin'?'VulcanIQ Admin':'VulcanIQ';
  const installRoute=variant==='admin'?'/admin/install':'/install';
  return <section className="notifications-card"><h2>{c(lang,'Installa','Install')} {name}</h2>
    {variant==='admin'&&<p className="small-note">{c(lang,'Per mantenere separata l’app Admin, installala da questa pagina Admin; la sua icona apre /admin.','To keep the Admin app separate, install it from this Admin page; its icon opens /admin.')}</p>}
    {state==='already_installed'&&<p className="notification-status success">{c(lang,'App già installata / aperta in modalità standalone.','App is already installed / running standalone.')}</p>}
    {state==='install_available'&&<button className="button primary" type="button" onClick={async()=>{await promptInstall();setState(installState());}}>{c(lang,`Installa ${name}`,`Install ${name}`)}</button>}
    {state==='needs_ios_home_screen'&&<div className="ios-install-guide"><p>{c(lang,'Su iPhone/iPad usa Safari:','On iPhone/iPad use Safari:')}</p><ol><li>{c(lang,<>Apri <a href={installRoute}>{installRoute}</a> in Safari.</>,<>Open <a href={installRoute}>{installRoute}</a> in Safari.</>)}</li><li>{c(lang,'Tocca Condividi.','Tap Share.')}</li><li>{c(lang,'Tocca Aggiungi alla schermata Home.','Tap Add to Home Screen.')}</li><li>{c(lang,'Conferma Aggiungi.','Confirm Add.')}</li><li>{c(lang,`Avvia ${name} dalla schermata Home.`,`Launch ${name} from the Home Screen.`)}</li><li>{c(lang,'Apri Installazione e notifiche.','Open Install & Notifications.')}</li><li>{c(lang,'Tocca Abilita notifiche.','Tap Enable notifications.')}</li></ol></div>}
    {state==='unsupported'&&<p>{c(lang,'Il browser non espone un prompt di installazione. Puoi continuare a usare il sito normalmente.','This browser does not expose an install prompt. You can continue using the website normally.')}</p>}
  </section>;
}

function Inbox({variant,lang,refreshKey}){
  const [items,setItems]=useState([]);const [error,setError]=useState('');
  async function load(){try{const data=await listNotificationInbox(variant);setItems(data.items||[]);setError('');}catch(err){if(err.status!==404)setError(err.message);}}
  useEffect(()=>{load();},[variant,refreshKey]);
  return <section className="notifications-card"><div className="notifications-card-head"><h2>{c(lang,'Centro notifiche','Notification center')}</h2><button type="button" className="button secondary" onClick={load}>{c(lang,'Aggiorna','Refresh')}</button></div>{error&&<p className="notification-error" role="alert">{error}</p>}{items.length===0?<p>{c(lang,'Nessuna notifica su questo dispositivo.','No notifications on this device.')}</p>:<div className="notification-inbox-list">{items.map(item=><article key={item.id} className={item.read_at?'read':'unread'}><div><strong>{item.title}</strong><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString(lang==='it'?'it-IT':'en-GB')}</small></div><div className="notification-item-actions">{!item.read_at&&<button type="button" onClick={async()=>{await markNotificationRead(variant,item.id);load();}}>{c(lang,'Letta','Mark read')}</button>}{item.destination_url&&<a className="button secondary" href={item.destination_url}>{c(lang,'Apri','Open')}</a>}<button type="button" onClick={async()=>{await dismissNotification(variant,item.id);load();}}>{c(lang,'Nascondi','Dismiss')}</button></div></article>)}</div>}</section>;
}

function CampaignComposer({lang,onSent}){
  const [form,setForm]=useState({category:'promotions',titleIt:'',bodyIt:'',titleEn:'',bodyEn:'',destinationUrl:'/',languageTarget:'all',scheduledFor:''});const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[items,setItems]=useState([]);
  async function load(){try{setItems((await listNotificationCampaigns()).items||[]);}catch{/* role may not support campaigns */}}
  useEffect(()=>{load();},[]);
  async function submit(){setSaving(true);setError('');try{await createNotificationCampaign({...form,scheduledFor:form.scheduledFor?new Date(form.scheduledFor).toISOString():''});setForm((v)=>({...v,titleIt:'',bodyIt:'',titleEn:'',bodyEn:'',scheduledFor:''}));await load();onSent?.();}catch(err){setError(err.message);}finally{setSaving(false);}}
  return <section className="notifications-card"><h2>{c(lang,'Componi notifica pubblica','Compose public notification')}</h2><p>{c(lang,'Per promozioni e copy marketing inserisci manualmente entrambe le lingue quando invii a tutti.','For promotions and marketing copy, enter both languages manually when sending to all users.')}</p><div className="notification-form-grid"><label><span>{c(lang,'Categoria','Category')}</span><select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))}><option value="promotions">{c(lang,'Promozioni e sconti','Promotions & discounts')}</option><option value="news">News</option><option value="events">{c(lang,'Eventi','Events')}</option><option value="experiences">{c(lang,'Esperienze','Experiences')}</option></select></label><label><span>{c(lang,'Lingua destinatari','Audience language')}</span><select value={form.languageTarget} onChange={e=>setForm(v=>({...v,languageTarget:e.target.value}))}><option value="all">IT + EN</option><option value="it">Italiano</option><option value="en">English</option></select></label><label><span>Titolo IT</span><input value={form.titleIt} maxLength={120} onChange={e=>setForm(v=>({...v,titleIt:e.target.value}))}/></label><label><span>Title EN</span><input value={form.titleEn} maxLength={120} onChange={e=>setForm(v=>({...v,titleEn:e.target.value}))}/></label><label className="full"><span>Testo IT</span><textarea value={form.bodyIt} maxLength={280} rows={3} onChange={e=>setForm(v=>({...v,bodyIt:e.target.value}))}/></label><label className="full"><span>Body EN</span><textarea value={form.bodyEn} maxLength={280} rows={3} onChange={e=>setForm(v=>({...v,bodyEn:e.target.value}))}/></label><label><span>URL</span><input value={form.destinationUrl} onChange={e=>setForm(v=>({...v,destinationUrl:e.target.value}))}/></label><label><span>{c(lang,'Programma (opzionale)','Schedule (optional)')}</span><input type="datetime-local" value={form.scheduledFor} onChange={e=>setForm(v=>({...v,scheduledFor:e.target.value}))}/></label></div><div className="campaign-preview" aria-label={c(lang,'Anteprima','Preview')}><strong>{form.titleIt||form.titleEn||c(lang,'Titolo anteprima','Preview title')}</strong><p>{form.bodyIt||form.bodyEn||c(lang,'Testo anteprima','Preview body')}</p></div>{error&&<p className="notification-error" role="alert">{error}</p>}<button className="button primary" type="button" disabled={saving} onClick={submit}>{saving?c(lang,'Invio...','Sending...'):form.scheduledFor?c(lang,'Programma','Schedule'):c(lang,'Invia ora','Send now')}</button>{items.length>0&&<details><summary>{c(lang,'Campagne recenti','Recent campaigns')}</summary>{items.slice(0,10).map(item=><p key={item.id} className="small-note">{item.category} · {item.status} · {item.created_at}</p>)}</details>}</section>;
}

export default function NotificationsPage({variant='public',lang='it',adminRole=''}){
  const [prefs,setPrefs]=useState({languagePreference:'auto',categories:defaultCategories(variant),quietHoursEnabled:false,quietStart:'22:00',quietEnd:'07:00'});const[deviceRegistered,setDeviceRegistered]=useState(false);const[pushEnabled,setPushEnabled]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[refreshKey,setRefreshKey]=useState(0);const[health,setHealth]=useState(null);
  const options=variant==='admin'?ADMIN_OPTIONS:PUBLIC_OPTIONS;const capability=capabilityState();const promoSelected=prefs.categories.includes('promotions');
  async function load(){try{await ensureNotificationDevice(variant,lang);setDeviceRegistered(true);const result=await getNotificationPreferences(variant);setPrefs(p=>({...p,...result.preferences}));setPushEnabled(Boolean(result.pushEnabled));}catch(err){if(err.status!==401)setError(err.message);}if(variant==='admin'){try{setHealth(await getNotificationHealth());}catch{/* non-fatal */}}}
  useEffect(()=>{load();},[variant]);
  useEffect(()=>{if(deviceRegistered&&prefs.languagePreference==='auto')updateNotificationPreferences(variant,prefs,lang).catch(()=>{});},[lang,deviceRegistered]);
  function toggleCategory(key){setPrefs(p=>({...p,categories:p.categories.includes(key)?p.categories.filter(v=>v!==key):[...p.categories,key]}));}
  async function enable(){setBusy(true);setError('');setMessage('');try{await enableNotifications({variant,currentLanguage:lang,...prefs});setPushEnabled(true);setDeviceRegistered(true);setMessage(c(lang,'Notifiche abilitate su questo dispositivo.','Notifications enabled on this device.'));setRefreshKey(v=>v+1);}catch(err){setError(err.code==='notification_permission_denied'?c(lang,'Permesso notifiche negato nelle impostazioni del browser/dispositivo.','Notification permission is denied in browser/device settings.'):err.message);}finally{setBusy(false);}}
  async function save(){setBusy(true);setError('');try{await updateNotificationPreferences(variant,prefs,lang);setMessage(c(lang,'Preferenze salvate.','Preferences saved.'));}catch(err){setError(err.message);}finally{setBusy(false);}}
  async function disable(){setBusy(true);try{await disableNotifications(variant);setPushEnabled(false);setMessage(c(lang,'Notifiche push disabilitate. Il centro notifiche in-app resta attivo su questo dispositivo.','Push notifications disabled. The in-app notification center remains active on this device.'));}catch(err){setError(err.message);}finally{setBusy(false);}}
  async function test(){setBusy(true);setError('');try{const result=await sendTestNotification(variant);setMessage(result.pushSkipped?c(lang,'Test aggiunto al centro notifiche in-app.','Test added to the in-app notification center.'):c(lang,'Notifica di test inviata.','Test notification sent.'));setRefreshKey(v=>v+1);}catch(err){setError(err.status===429?c(lang,'Attendi circa un minuto prima di un altro test.','Wait about one minute before another test.'):err.message);}finally{setBusy(false);}}
  return <div className="notifications-page"><header className="notifications-hero"><span className="kicker">{variant==='admin'?'VulcanIQ Admin':'VulcanIQ'}</span><h1>{c(lang,'Installazione e notifiche','Install & Notifications')}</h1><p>{variant==='public'?c(lang,'Scegli gli aggiornamenti che vuoi ricevere su questo dispositivo. VulcanIQ non è un servizio di allerta di emergenza o protezione civile.','Choose the updates you want on this device. VulcanIQ is not an emergency or civil-protection warning service.'):c(lang,'Le notifiche Admin usano messaggi generici sulla schermata di blocco; i dettagli rimangono nell’area autenticata.','Admin lock-screen notifications use generic messages; full details remain in the authenticated area.')}</p></header>
    <InstallCard variant={variant} lang={lang}/><section className="notifications-card"><div className="notifications-card-head"><h2>{c(lang,'Preferenze','Preferences')}</h2><span className={`notification-status ${deviceRegistered?'success':''}`}>{pushEnabled?c(lang,'Push attivo','Push enabled'):deviceRegistered?c(lang,'Centro in-app attivo','In-app center active'):capability}</span></div><label><span>{c(lang,'Lingua notifiche','Notification language')}</span><select value={prefs.languagePreference} onChange={e=>setPrefs(p=>({...p,languagePreference:e.target.value}))}><option value="auto">{c(lang,'Automatico','Automatic')}</option><option value="it">Italiano</option><option value="en">English</option></select></label><fieldset><legend>{variant==='admin'?c(lang,'Categorie Admin','Admin categories'):c(lang,'Categorie pubbliche','Public categories')}</legend>{options.map(([key,en,it])=><label className="notification-toggle" key={key}><input type="checkbox" checked={prefs.categories.includes(key)} onChange={()=>toggleCategory(key)}/><span>{lang==='it'?it:en}</span></label>)}</fieldset>{variant==='public'&&<p className="small-note">{c(lang,`Le promozioni sono ${promoSelected?'attive':'disattivate'} separatamente dal permesso push.`,`Promotions are ${promoSelected?'enabled':'disabled'} separately from push permission.`)}</p>}<label className="notification-toggle"><input type="checkbox" checked={prefs.quietHoursEnabled} onChange={e=>setPrefs(p=>({...p,quietHoursEnabled:e.target.checked}))}/><span>{c(lang,'Ore silenziose','Quiet hours')}</span></label>{prefs.quietHoursEnabled&&<div className="quiet-hours"><label><span>{c(lang,'Da','From')}</span><input type="time" value={prefs.quietStart||''} onChange={e=>setPrefs(p=>({...p,quietStart:e.target.value}))}/></label><label><span>{c(lang,'A','To')}</span><input type="time" value={prefs.quietEnd||''} onChange={e=>setPrefs(p=>({...p,quietEnd:e.target.value}))}/></label></div>}{error&&<p className="notification-error" role="alert">{error}</p>}{message&&<p className="notification-status success" role="status">{message}</p>}<div className="notification-actions"><button className="button primary" type="button" disabled={busy||!deviceRegistered} onClick={save}>{c(lang,'Salva preferenze','Save preferences')}</button><button className="button secondary" type="button" disabled={busy||!deviceRegistered} onClick={test}>{c(lang,'Invia test','Send test')}</button>{!pushEnabled?<button className="button secondary" type="button" disabled={busy||capability==='unsupported'||capability==='permission_denied'} onClick={enable}>{c(lang,'Abilita notifiche push','Enable push notifications')}</button>:<button className="button secondary" type="button" disabled={busy} onClick={disable}>{c(lang,'Disabilita push','Disable push')}</button>}</div></section>
    <Inbox variant={variant} lang={lang} refreshKey={refreshKey}/>{variant==='admin'&&<><section className="notifications-card"><h2>{c(lang,'Salute sistema notifiche','Notification system health')}</h2>{health?<div className="health-grid"><span><small>{c(lang,'Modalità budget','Budget mode')}</small><strong>{health.budget?.mode||'-'}</strong></span><span><small>{c(lang,'Tentativi push oggi','Push attempts today')}</small><strong>{health.counters?.push_attempts||0}</strong></span><span><small>{c(lang,'Invii riusciti','Successful sends')}</small><strong>{health.counters?.push_success||0}</strong></span><span><small>{c(lang,'Falliti','Failed')}</small><strong>{health.counters?.push_failed||0}</strong></span></div>:<p>{c(lang,'Dati salute non disponibili.','Health data unavailable.')}</p>}<p className="small-note">{c(lang,'I contatori sono interni e conservativi; non sostituiscono la fatturazione Cloudflare.', 'Counters are internal and conservative; they do not replace Cloudflare billing usage.')}</p></section>{['owner','manager'].includes(adminRole)&&<CampaignComposer lang={lang} onSent={()=>setRefreshKey(v=>v+1)}/>}</>}</div>;
}
